FROM pennsieve/pennsieve-agent:1.4.5

RUN apk update && apk upgrade

WORKDIR /service/

RUN cp /root/pennsieve /usr/local/bin/

ENV PATH="${PATH}:/usr/local/bin"

# install Go
RUN wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz

RUN  rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz

ENV PATH="${PATH}:/usr/local/go/bin"

# cleanup
RUN rm -f go1.21.0.linux-amd64.tar.gz

COPY . ./
RUN GOARCH=amd64 GOOS=linux go build -o /service/bootstrap main.go

RUN apk --no-cache add curl


RUN mkdir /lambda

ENTRYPOINT [ "/service/entry_script.sh" ]